# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biped_receive_control_command.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_biped_receive_control_command(object):
    def setupUi(self, biped_receive_control_command):
        biped_receive_control_command.setObjectName("biped_receive_control_command")
        biped_receive_control_command.resize(552, 577)
        self.label_155 = QtWidgets.QLabel(biped_receive_control_command)
        self.label_155.setGeometry(QtCore.QRect(30, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_155.setFont(font)
        self.label_155.setObjectName("label_155")
        self.lineEdit_72 = QtWidgets.QLineEdit(biped_receive_control_command)
        self.lineEdit_72.setGeometry(QtCore.QRect(440, 370, 85, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_72.setFont(font)
        self.lineEdit_72.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_72.setReadOnly(True)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(biped_receive_control_command)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(220, 40, 181, 241))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_52.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_11.addWidget(self.lineEdit_52, 2, 1, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_112.setObjectName("label_112")
        self.gridLayout_11.addWidget(self.label_112, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_113 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_113.setObjectName("label_113")
        self.gridLayout_11.addWidget(self.label_113, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_114 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_114.setObjectName("label_114")
        self.gridLayout_11.addWidget(self.label_114, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_53.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_11.addWidget(self.lineEdit_53, 3, 1, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_115.setObjectName("label_115")
        self.gridLayout_11.addWidget(self.label_115, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_116 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_116.setObjectName("label_116")
        self.gridLayout_11.addWidget(self.label_116, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_50.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_11.addWidget(self.lineEdit_50, 0, 1, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_117.setObjectName("label_117")
        self.gridLayout_11.addWidget(self.label_117, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_118 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_118.setObjectName("label_118")
        self.gridLayout_11.addWidget(self.label_118, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_119 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_119.setObjectName("label_119")
        self.gridLayout_11.addWidget(self.label_119, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_55.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_11.addWidget(self.lineEdit_55, 5, 1, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_120.setObjectName("label_120")
        self.gridLayout_11.addWidget(self.label_120, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_121 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_121.setObjectName("label_121")
        self.gridLayout_11.addWidget(self.label_121, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_54.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_11.addWidget(self.lineEdit_54, 4, 1, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_122.setObjectName("label_122")
        self.gridLayout_11.addWidget(self.label_122, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_123 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_123.setObjectName("label_123")
        self.gridLayout_11.addWidget(self.label_123, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_51.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_11.addWidget(self.lineEdit_51, 1, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(biped_receive_control_command)
        self.pushButton_21.setGeometry(QtCore.QRect(430, 190, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_5 = QtWidgets.QLabel(biped_receive_control_command)
        self.label_5.setGeometry(QtCore.QRect(230, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(biped_receive_control_command)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(20, 40, 181, 241))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_40.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_9.addWidget(self.lineEdit_40, 2, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_87.setObjectName("label_87")
        self.gridLayout_9.addWidget(self.label_87, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_88 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_88.setObjectName("label_88")
        self.gridLayout_9.addWidget(self.label_88, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_89 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_89.setObjectName("label_89")
        self.gridLayout_9.addWidget(self.label_89, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_41.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_9.addWidget(self.lineEdit_41, 3, 1, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_90.setObjectName("label_90")
        self.gridLayout_9.addWidget(self.label_90, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_91 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_91.setObjectName("label_91")
        self.gridLayout_9.addWidget(self.label_91, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_38.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_9.addWidget(self.lineEdit_38, 0, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_92.setObjectName("label_92")
        self.gridLayout_9.addWidget(self.label_92, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_93 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_93.setObjectName("label_93")
        self.gridLayout_9.addWidget(self.label_93, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_94 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_94.setObjectName("label_94")
        self.gridLayout_9.addWidget(self.label_94, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_43.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_9.addWidget(self.lineEdit_43, 5, 1, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_95.setObjectName("label_95")
        self.gridLayout_9.addWidget(self.label_95, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_96 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_96.setObjectName("label_96")
        self.gridLayout_9.addWidget(self.label_96, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_42.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_9.addWidget(self.lineEdit_42, 4, 1, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_97.setObjectName("label_97")
        self.gridLayout_9.addWidget(self.label_97, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_98 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_98.setObjectName("label_98")
        self.gridLayout_9.addWidget(self.label_98, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_39.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_9.addWidget(self.lineEdit_39, 1, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(biped_receive_control_command)
        self.pushButton_19.setGeometry(QtCore.QRect(430, 50, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_100 = QtWidgets.QLabel(biped_receive_control_command)
        self.label_100.setGeometry(QtCore.QRect(230, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(biped_receive_control_command)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(20, 340, 171, 221))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_128 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_128.setObjectName("label_128")
        self.gridLayout_14.addWidget(self.label_128, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_130 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_130.setObjectName("label_130")
        self.gridLayout_14.addWidget(self.label_130, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_140 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_140.setObjectName("label_140")
        self.gridLayout_14.addWidget(self.label_140, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_142 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_142.setObjectName("label_142")
        self.gridLayout_14.addWidget(self.label_142, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_149 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_149.setObjectName("label_149")
        self.gridLayout_14.addWidget(self.label_149, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_150 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_150.setObjectName("label_150")
        self.gridLayout_14.addWidget(self.label_150, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_151 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_151.setObjectName("label_151")
        self.gridLayout_14.addWidget(self.label_151, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_152 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_152.setObjectName("label_152")
        self.gridLayout_14.addWidget(self.label_152, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_153 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_153.setObjectName("label_153")
        self.gridLayout_14.addWidget(self.label_153, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_154 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_154.setObjectName("label_154")
        self.gridLayout_14.addWidget(self.label_154, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_70.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_70.setReadOnly(True)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.gridLayout_14.addWidget(self.lineEdit_70, 5, 1, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_59.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_59.setReadOnly(True)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_14.addWidget(self.lineEdit_59, 0, 1, 1, 1)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_69.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_69.setReadOnly(True)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.gridLayout_14.addWidget(self.lineEdit_69, 4, 1, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_65.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_65.setReadOnly(True)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout_14.addWidget(self.lineEdit_65, 1, 1, 1, 1)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_68.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_68.setReadOnly(True)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.gridLayout_14.addWidget(self.lineEdit_68, 2, 1, 1, 1)
        self.gridLayoutWidget_14 = QtWidgets.QWidget(biped_receive_control_command)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(220, 340, 171, 221))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_156 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_156.setFont(font)
        self.label_156.setObjectName("label_156")
        self.gridLayout_15.addWidget(self.label_156, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_157 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_157.setObjectName("label_157")
        self.gridLayout_15.addWidget(self.label_157, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_158 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_158.setObjectName("label_158")
        self.gridLayout_15.addWidget(self.label_158, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_159 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_159.setObjectName("label_159")
        self.gridLayout_15.addWidget(self.label_159, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_160 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_160.setObjectName("label_160")
        self.gridLayout_15.addWidget(self.label_160, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_161 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_161.setFont(font)
        self.label_161.setObjectName("label_161")
        self.gridLayout_15.addWidget(self.label_161, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_162 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_162.setObjectName("label_162")
        self.gridLayout_15.addWidget(self.label_162, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_163 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_163.setFont(font)
        self.label_163.setObjectName("label_163")
        self.gridLayout_15.addWidget(self.label_163, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_164 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_164.setFont(font)
        self.label_164.setObjectName("label_164")
        self.gridLayout_15.addWidget(self.label_164, 1, 0, 1, 1)
        self.label_165 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.gridLayout_15.addWidget(self.label_165, 0, 0, 1, 1)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_71.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_71.setReadOnly(True)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.gridLayout_15.addWidget(self.lineEdit_71, 0, 1, 1, 1)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_74.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_74.setReadOnly(True)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.gridLayout_15.addWidget(self.lineEdit_74, 2, 1, 1, 1)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_75.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_75.setReadOnly(True)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.gridLayout_15.addWidget(self.lineEdit_75, 3, 1, 1, 1)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_73.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_73.setReadOnly(True)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.gridLayout_15.addWidget(self.lineEdit_73, 1, 1, 1, 1)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_76.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_76.setReadOnly(True)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.gridLayout_15.addWidget(self.lineEdit_76, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(biped_receive_control_command)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(biped_receive_control_command)
        self.label_8.setGeometry(QtCore.QRect(420, 340, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(biped_receive_control_command)
        self.pushButton_21.clicked['bool'].connect(biped_receive_control_command.receive_data)
        self.pushButton_19.clicked['bool'].connect(biped_receive_control_command.send_now_robot_deacarte_data)
        QtCore.QMetaObject.connectSlotsByName(biped_receive_control_command)

    def retranslateUi(self, biped_receive_control_command):
        _translate = QtCore.QCoreApplication.translate
        biped_receive_control_command.setWindowTitle(_translate("biped_receive_control_command", "爬壁机器人接收控制命令窗口"))
        self.label_155.setText(_translate("biped_receive_control_command", "转换后关节位置命令"))
        self.lineEdit_72.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_52.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_112.setText(_translate("biped_receive_control_command", "Y"))
        self.label_113.setText(_translate("biped_receive_control_command", "Z"))
        self.label_114.setText(_translate("biped_receive_control_command", "X"))
        self.lineEdit_53.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_115.setText(_translate("biped_receive_control_command", "deg"))
        self.label_116.setText(_translate("biped_receive_control_command", "RZ"))
        self.lineEdit_50.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_117.setText(_translate("biped_receive_control_command", "mm"))
        self.label_118.setText(_translate("biped_receive_control_command", "deg"))
        self.label_119.setText(_translate("biped_receive_control_command", "deg"))
        self.lineEdit_55.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_120.setText(_translate("biped_receive_control_command", "mm"))
        self.label_121.setText(_translate("biped_receive_control_command", "mm"))
        self.lineEdit_54.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_122.setText(_translate("biped_receive_control_command", "RX"))
        self.label_123.setText(_translate("biped_receive_control_command", "RY"))
        self.lineEdit_51.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.pushButton_21.setText(_translate("biped_receive_control_command", "接收数据"))
        self.label_5.setText(_translate("biped_receive_control_command", "到基座笛卡尔位置显示"))
        self.lineEdit_40.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_87.setText(_translate("biped_receive_control_command", "Y"))
        self.label_88.setText(_translate("biped_receive_control_command", "Z"))
        self.label_89.setText(_translate("biped_receive_control_command", "X"))
        self.lineEdit_41.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_90.setText(_translate("biped_receive_control_command", "deg"))
        self.label_91.setText(_translate("biped_receive_control_command", "RZ"))
        self.lineEdit_38.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_92.setText(_translate("biped_receive_control_command", "mm"))
        self.label_93.setText(_translate("biped_receive_control_command", "deg"))
        self.label_94.setText(_translate("biped_receive_control_command", "deg"))
        self.lineEdit_43.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_95.setText(_translate("biped_receive_control_command", "mm"))
        self.label_96.setText(_translate("biped_receive_control_command", "mm"))
        self.lineEdit_42.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_97.setText(_translate("biped_receive_control_command", "RX"))
        self.label_98.setText(_translate("biped_receive_control_command", "RY"))
        self.lineEdit_39.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.pushButton_19.setText(_translate("biped_receive_control_command", "发送笛卡尔\n"
"位姿命令"))
        self.label_100.setText(_translate("biped_receive_control_command", "转换后关节速度命令"))
        self.label_128.setText(_translate("biped_receive_control_command", "I1"))
        self.label_130.setText(_translate("biped_receive_control_command", "T2"))
        self.label_140.setText(_translate("biped_receive_control_command", "T3"))
        self.label_142.setText(_translate("biped_receive_control_command", "deg"))
        self.label_149.setText(_translate("biped_receive_control_command", "deg"))
        self.label_150.setText(_translate("biped_receive_control_command", "deg"))
        self.label_151.setText(_translate("biped_receive_control_command", "deg"))
        self.label_152.setText(_translate("biped_receive_control_command", "I5"))
        self.label_153.setText(_translate("biped_receive_control_command", "deg"))
        self.label_154.setText(_translate("biped_receive_control_command", "T4"))
        self.lineEdit_70.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_59.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_69.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_65.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_68.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_156.setText(_translate("biped_receive_control_command", "T3"))
        self.label_157.setText(_translate("biped_receive_control_command", "deg/s"))
        self.label_158.setText(_translate("biped_receive_control_command", "deg/s"))
        self.label_159.setText(_translate("biped_receive_control_command", "deg/s"))
        self.label_160.setText(_translate("biped_receive_control_command", "deg/s"))
        self.label_161.setText(_translate("biped_receive_control_command", "T4"))
        self.label_162.setText(_translate("biped_receive_control_command", "deg/s"))
        self.label_163.setText(_translate("biped_receive_control_command", "I5"))
        self.label_164.setText(_translate("biped_receive_control_command", "T2"))
        self.label_165.setText(_translate("biped_receive_control_command", "I1"))
        self.lineEdit_71.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_74.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_75.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_73.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_76.setToolTip(_translate("biped_receive_control_command", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_3.setText(_translate("biped_receive_control_command", "接收笛卡尔位置显示"))
        self.label_8.setText(_translate("biped_receive_control_command", "转换后是否正确"))

