# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modular_robot_control.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_modular_robot(object):
    def setupUi(self, MainWindow_modular_robot):
        MainWindow_modular_robot.setObjectName("MainWindow_modular_robot")
        MainWindow_modular_robot.resize(689, 521)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_modular_robot.sizePolicy().hasHeightForWidth())
        MainWindow_modular_robot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow_modular_robot.setFont(font)
        MainWindow_modular_robot.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow_modular_robot)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 401, 470))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, -10, 351, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 4, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 350, 351, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout.addWidget(self.lineEdit_12)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 291, 411))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_24.setGeometry(QtCore.QRect(310, 240, 80, 80))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(310, 90, 80, 80))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(440, 50, 231, 291))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_3.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 4, 2, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 3, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_3.addWidget(self.lineEdit_16, 4, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 0, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_3.addWidget(self.lineEdit_17, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(570, 430, 100, 60))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(440, 430, 100, 60))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(570, 350, 100, 60))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(440, 350, 100, 60))
        self.pushButton_12.setObjectName("pushButton_12")
        MainWindow_modular_robot.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_modular_robot)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 40))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow_modular_robot.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_2.setFont(font)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_3.setFont(font)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_5.setFont(font)
        self.action_5.setObjectName("action_5")
        self.action_8 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_8.setFont(font)
        self.action_8.setObjectName("action_8")
        self.action_4 = QtWidgets.QAction(MainWindow_modular_robot)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_8)
        self.menu_4.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow_modular_robot)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow_modular_robot.joint_i1_command)
        self.pushButton_2.clicked.connect(MainWindow_modular_robot.joint_t2_command)
        self.pushButton_3.clicked.connect(MainWindow_modular_robot.joint_t3_command)
        self.pushButton_4.clicked.connect(MainWindow_modular_robot.joint_t4_command)
        self.pushButton_5.clicked.connect(MainWindow_modular_robot.joint_i5_command)
        self.pushButton_6.clicked.connect(MainWindow_modular_robot.joint_velocity_set)
        self.pushButton_8.clicked.connect(MainWindow_modular_robot.quick_stop)
        self.pushButton_7.clicked['bool'].connect(MainWindow_modular_robot.halt)
        self.pushButton_11.clicked.connect(MainWindow_modular_robot.load_point_file)
        self.pushButton_24.clicked.connect(MainWindow_modular_robot.operate_point_data)
        self.pushButton_10.clicked.connect(MainWindow_modular_robot.stop_robot)
        self.pushButton_12.clicked.connect(MainWindow_modular_robot.start_robot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_modular_robot)

    def retranslateUi(self, MainWindow_modular_robot):
        _translate = QtCore.QCoreApplication.translate
        self.lineEdit_9.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-120~120度</p></body></html>"))
        self.label_14.setText(_translate("MainWindow_modular_robot", "关节_T2"))
        self.label_20.setText(_translate("MainWindow_modular_robot", "度"))
        self.label_15.setText(_translate("MainWindow_modular_robot", "关节_T3"))
        self.label_18.setText(_translate("MainWindow_modular_robot", "度"))
        self.lineEdit_11.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_8.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-120~120度</p></body></html>"))
        self.label_21.setText(_translate("MainWindow_modular_robot", "度"))
        self.label_16.setText(_translate("MainWindow_modular_robot", "关节_T4"))
        self.lineEdit_7.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_19.setText(_translate("MainWindow_modular_robot", "度"))
        self.pushButton_5.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_2.setText(_translate("MainWindow_modular_robot", "运行"))
        self.label_13.setText(_translate("MainWindow_modular_robot", "关节_I1"))
        self.label_17.setText(_translate("MainWindow_modular_robot", "关节_I5"))
        self.pushButton_3.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_4.setText(_translate("MainWindow_modular_robot", "运行"))
        self.label_22.setText(_translate("MainWindow_modular_robot", "度"))
        self.lineEdit_10.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-120~120度</p></body></html>"))
        self.label_23.setText(_translate("MainWindow_modular_robot", "关节速度"))
        self.lineEdit_12.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p align=\"center\">1~30度/秒</p></body></html>"))
        self.label_24.setText(_translate("MainWindow_modular_robot", "度/秒"))
        self.pushButton_6.setText(_translate("MainWindow_modular_robot", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_modular_robot", "关节空间控制"))
        self.pushButton_24.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_11.setText(_translate("MainWindow_modular_robot", "载入\n"
"文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_modular_robot", "离线轨迹点控制"))
        self.label_25.setText(_translate("MainWindow_modular_robot", "度"))
        self.label_26.setText(_translate("MainWindow_modular_robot", "度"))
        self.label_27.setText(_translate("MainWindow_modular_robot", "关节_T4"))
        self.label_28.setText(_translate("MainWindow_modular_robot", "关节_T3"))
        self.label_29.setText(_translate("MainWindow_modular_robot", "关节_I5"))
        self.label_30.setText(_translate("MainWindow_modular_robot", "度"))
        self.label_31.setText(_translate("MainWindow_modular_robot", "关节_T2"))
        self.label_32.setText(_translate("MainWindow_modular_robot", "度"))
        self.label_33.setText(_translate("MainWindow_modular_robot", "关节_I1"))
        self.label_34.setText(_translate("MainWindow_modular_robot", "度"))
        self.pushButton_8.setText(_translate("MainWindow_modular_robot", "急停"))
        self.pushButton_7.setText(_translate("MainWindow_modular_robot", "暂停 "))
        self.label.setText(_translate("MainWindow_modular_robot", "机器人未使能"))
        self.pushButton_10.setText(_translate("MainWindow_modular_robot", "停止"))
        self.pushButton_12.setText(_translate("MainWindow_modular_robot", "启动"))
        self.menu.setTitle(_translate("MainWindow_modular_robot", "文件"))
        self.menu_2.setTitle(_translate("MainWindow_modular_robot", "工具"))
        self.menu_4.setTitle(_translate("MainWindow_modular_robot", "帮助"))
        self.action.setText(_translate("MainWindow_modular_robot", "夹持器"))
        self.action_2.setText(_translate("MainWindow_modular_robot", "示教点记录"))
        self.action_3.setText(_translate("MainWindow_modular_robot", "零点设置"))
        self.action_5.setText(_translate("MainWindow_modular_robot", "退出"))
        self.action_8.setText(_translate("MainWindow_modular_robot", "自主抓夹"))
        self.action_4.setText(_translate("MainWindow_modular_robot", "关于"))

